### ISSUE TITLE
Donate flow: very strange 500 error after trying to donate

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#198]
<img width="1062" alt="Screen Shot 2021-10-09 at 4 04 16 PM" src="https://user-images.githubusercontent.com/68758055/136672460-87b3e375-b79c-4870-a45b-2dda63523042.png">

**Comment by 1stevengrant** [comment]
@joenicolette we'll need to update our account with Chipper CI to sort this. $39 a month. I'll send you the credentials for the account.

**Comment by 1stevengrant** [comment]
@joenicolette Chipper all good and doing its things 🎉

**Comment by 1stevengrant** [comment]
Can you do me a favour please @gitethanwoo and try another email address? I'm wondering if that might be causing an issue.

**Comment by gitethanwoo** [comment]
@1stevengrant  you were right.... It works with my other email

**Comment by 1stevengrant** [comment]
So what's happening here is that previously, you'd have done this and used that email address that gets an initial customer id.

Because we're doing things in another environment, the customer id that's assigned to your email address is no longer valid. 

Given we're in test, and new donations are fine, we can close this one out.

**Comment by gitethanwoo** [comment]
Great. This should also close out Joe's error as well.
