### ISSUE TITLE
Dev - Only serve up "Champion" labeled content to logged in/Champion accounts

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#258]
<img width="360" alt="Screen Shot 2021-10-21 at 8 31 47 PM" src="https://user-images.githubusercontent.com/82427400/138374828-778873e9-2282-41e1-b300-d7e29666a670.png">

**Comment by 1stevengrant** [comment]
will resolve on next deploy

**Comment by joenicolette** [comment]
Hmm...how do I tag a video as Champions-specific? I see a "Champions" and "Champion-Specific" categorical tag but they don't seem to be working, as far as revealing the "CHAMPIONS" icon

**Comment by joenicolette** [comment]
Ok! This works. Champion-Specific tagged videos are no longer appearing on the homepage when logged out. 

~BUT~

I'm still able to access the videos, even while logged out by typing in an author "David Olsen" and viewing his videos.
The video shown is also not showing any iconography over it, even though it's supposed to be for champions only.
<img width="818" alt="Screen Shot 2021-10-30 at 9 06 20 PM" src="https://user-images.githubusercontent.com/82427400/139562753-a975bf9b-6b05-40ca-a9b7-8a7cf5fb379b.png">

**Comment by 1stevengrant** [comment]
good call...forgot all the places the videos are surfaced...will resolve in next deploy

**Comment by joenicolette** [comment]
Making huge progress with this logic. @gitethanwoo - any input on how we can clean up this look? Do we want to show this at all to a user who's not signed in?

<img width="331" alt="Screen Shot 2021-10-31 at 2 01 05 PM" src="https://user-images.githubusercontent.com/82427400/139596117-a1b1fffa-ae29-4dff-81b7-e5547556728a.png">

**Comment by 1stevengrant** [comment]
I think we need this otherwise, the browse section is empty.

Sent with a Spark

**Comment by gitethanwoo** [comment]
So it looks like David Olson is the **only** expert who, for the time being, will have champion-specific content without couple-facing content. I propose a simple solution for this one-off case.

Is this possible and easy enough? I'm trying to provide a good, on-brand solution that's low effort because this is a one-off situation.

![Screen Shot 2021-11-01 at 11 32 42 AM](https://user-images.githubusercontent.com/68758055/139697923-2b190fba-bcfd-404c-b847-a7011fa359d5.png)

**Comment by 1stevengrant** [comment]
not really @gitethanwoo - David doesn't have his own page...each of these profiles is shared between all experts, whatever we do for one, we do for the other. `Browse` here shows all videos belonging to an author, regardless of who they're for.

Same goes for the video pages.

**Comment by gitethanwoo** [comment]
Ah I see. In this case, how have you put in this custom message for that video?

**Comment by 1stevengrant** [comment]
so when the author is pulled from the database, it pulls the videos that author owns. Then the logic works like this

```
if $video->canBeSeenByCurrentUser
  show the video card
else
  show the alternative placeholder
endif
```

that particular section is set to use an auto grid that is 2 cols and then 3 cols on desktop, so that alternative placeholder takes up 1 of those grid columns. If, for example, they had 2 videos that were for champions only, it would show 2 placeholders.

**Comment by gitethanwoo** [comment]
Would this happen for every author? I don't want this type of message to show up over every champion video for every author on non-champion accounts

**Comment by 1stevengrant** [comment]
it would yeah, can't think of another solution

**Comment by 1stevengrant** [comment]
@joenicolette @gitethanwoo @garethredfern I'm open to all ideas on this one. Possible I've been noddling on it for too long.

**Comment by joenicolette** [comment]
Ben mentioned today that "there’s no reason to add the “this video is for marriage champions” badge. We just shouldn't show the thumbnail.

**Comment by 1stevengrant** [comment]
done for next deploy

**Comment by gitethanwoo** [comment]
Cool
