### ISSUE TITLE
Search - Items populating twice?

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#325]
<img width="1575" alt="Screen Shot 2021-11-03 at 2 23 14 PM" src="https://user-images.githubusercontent.com/82427400/140170043-f8224b24-641f-4b5c-ae7b-93ec87c5d18c.png">

**Comment by 1stevengrant** [comment]
yeah, @joenicolette - search is actually off. If you login to Algolia itself, it's returning the kind of results you'd expect. I'll need to dive a bit on this

**Comment by 1stevengrant** [comment]
for future me: super happy that this came up. Algolia have introduced a feature that allows us to perform a search query from outside of their instance. We can use the `<ais-configure :query="searchQuery" />` to perform a search based on a query in Vuex. Means that rather than configuring instantsearch.js manually, we get the benefit of pre-configured Vue components 🎉

for @joenicolette fix coming in the next deployment. Note that I've removed the `sort by` options because it actually doesn't make any sense in this context where we're returning `videos` and `experts` you can't sort an expert by `most played` or `most viewed` - we should look to introduce `resources`, `webinars` and `assessments` into this list as well.

**Comment by gitethanwoo** [comment]
How difficult would it be to just add headers for right now, like shown in this screenshot?

![Screen Shot 2021-11-04 at 12 48 58 PM](https://user-images.githubusercontent.com/68758055/140382948-1e3b2cec-6e82-4525-9168-ff7498a5a982.png)

**Comment by gitethanwoo** [comment]
I love how the search feels now.. A lot better. I think if we had some headers it would be perfect

**Comment by 1stevengrant** [comment]
Headers I thought about and an easy add. Actually solves my dislike of having each thing separately - but it's still a single search index that nullifies the sort by options.

**Comment by 1stevengrant** [comment]
next deploy

**Comment by joenicolette** [comment]
Hmm...
<img width="1515" alt="Screen Shot 2021-11-06 at 10 10 43 PM" src="https://user-images.githubusercontent.com/82427400/140629716-7c76eeac-6d2f-47d3-9677-216350344b1d.png">

**Comment by 1stevengrant** [comment]
@joenicolette Gareth hadn't yet merged this into to the codebase so was still the same. Coming on next deploy.
