### ISSUE TITLE
MOBILE: Explore section

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#58]
The text/thumbnails cut off on the top portion of this component are not a good experience, IMO. The comps in Figma don't seem to be cut off. Interesting!

![IMG_BB9833F5E016-1](https://user-images.githubusercontent.com/82427400/115640949-201ecf80-a2e6-11eb-8f9d-80ac0345fd29.jpeg)

**Comment by 1stevengrant** [comment]
yeah, I applied that because right now the iPhone explore image is 375 wide but the large iPhones are 414. I'll stop the cut-off and we can change the image because it has the cream either side.

![simulator_screenshot_C04972A1-94EA-4887-A900-B65B861CFDEB](https://user-images.githubusercontent.com/112473/115735231-38442c80-a382-11eb-900d-2636bbc5bde1.png)
