### ISSUE TITLE
The email input field should be about the same height as the button ~ 34 pixels high

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#80]
![Screen Shot 2021-05-12 at 12 40 17 PM](https://user-images.githubusercontent.com/68758055/118012661-4c46d280-b31f-11eb-9384-0a4a2e654239.png)

**Comment by 1stevengrant** [comment]
We'll only have 1 input component throughout the site and we don't set the height. Height is set by the content within, plus a little y vertical padding. I've reduced the y padding.

Similarly, I'd like us to have a single button component that has size & color variants so that we have consistency with all of the buttons styles. There's a degree of that right now but can be tighter for sure.

**Comment by gitethanwoo** [comment]
![IMG_D24235E19588-1](https://user-images.githubusercontent.com/68758055/118312807-ed6c8f00-b4bf-11eb-9b7a-6bf358f47ce7.jpeg)
 
That's on my to-do list!!!! I'm excited to create those components just so we have a consistent experience throughout the entire site

**Comment by 1stevengrant** [comment]
design systems are niiiiicccce. It's been my buddy Dan's whole thing for a while https://superfriendlydesign.systems/classes/
